import type { CategoryDefinition } from "./types";

export const TAXONOMY: CategoryDefinition[] = [
  { id: "development", name: "开发编程", color: "blue", domains: ["github.com", "gitlab.com", "bitbucket.org", "stackoverflow.com", "stackexchange.com", "npmjs.com", "pypi.org", "crates.io", "docker.com", "hub.docker.com", "vercel.com", "netlify.com", "cloudflare.com"], domainSuffixes: ["github.io"], titleKeywords: ["github", "gitlab", "stack overflow", "npm", "package", "issue", "pull request", "commit", "docker", "api", "sdk", "bug", "error", "exception", "typescript", "javascript", "python", "java", "spring", "vue", "react", "vite", "node", "编程", "代码", "仓库", "提交", "分支", "拉取请求", "报错", "异常"], urlKeywords: ["repo", "issues", "pull", "commit", "package", "docs", "api", "reference"], weightedKeywords: { react: 20, vue: 20, typescript: 20, javascript: 18, python: 18, java: 15, spring: 15, vite: 18, node: 18, error: 12, exception: 12 }, minScore: 40 },
  { id: "tech-docs", name: "技术文档", color: "cyan", domains: ["developer.chrome.com", "developer.mozilla.org", "docs.github.com", "react.dev", "vuejs.org", "vitejs.dev", "typescriptlang.org", "nodejs.org", "python.org", "spring.io", "tailwindcss.com"], domainSuffixes: [], titleKeywords: ["docs", "documentation", "guide", "tutorial", "reference", "api", "manual", "getting started", "quickstart", "文档", "指南", "教程", "参考", "接口", "手册"], urlKeywords: ["docs", "documentation", "guide", "reference", "api", "learn"], weightedKeywords: { docs: 25, documentation: 25, reference: 20, api: 18, guide: 15, 文档: 25, 教程: 15 }, minScore: 35 },
  { id: "ai-tools", name: "AI工具", color: "purple", domains: ["chatgpt.com", "claude.ai", "gemini.google.com", "poe.com", "perplexity.ai", "huggingface.co", "replicate.com", "openrouter.ai", "platform.openai.com"], domainSuffixes: [], titleKeywords: ["chatgpt", "claude", "gemini", "ai", "llm", "prompt", "model", "transformer", "embedding", "rag", "agent", "openai", "hugging face", "人工智能", "大模型", "提示词", "模型", "向量", "检索增强", "智能体"], urlKeywords: ["chat", "model", "playground", "prompt", "inference", "embeddings"], weightedKeywords: { chatgpt: 30, claude: 30, gemini: 30, llm: 25, prompt: 20, rag: 20, embedding: 15, 大模型: 25, 提示词: 20 }, minScore: 35 },
  { id: "papers", name: "论文资料", color: "green", domains: ["scholar.google.com", "arxiv.org", "ieee.org", "acm.org", "springer.com", "sciencedirect.com", "researchgate.net", "semanticscholar.org", "cnki.net", "wanfangdata.com.cn"], domainSuffixes: ["edu", "edu.cn"], titleKeywords: ["paper", "journal", "conference", "arxiv", "doi", "citation", "abstract", "references", "proceedings", "论文", "期刊", "会议", "文献", "摘要", "引用", "参考文献", "知网", "万方"], urlKeywords: ["paper", "abstract", "citation", "doi", "article", "proceedings"], weightedKeywords: { paper: 25, arxiv: 30, doi: 25, citation: 20, 论文: 30, 文献: 25, 参考文献: 25, 摘要: 15 }, minScore: 35 },
  { id: "learning", name: "学习课程", color: "yellow", domains: ["coursera.org", "edx.org", "udemy.com", "bilibili.com", "icourse163.org", "xuetangx.com", "mooc.org", "khanacademy.org"], domainSuffixes: [], titleKeywords: ["course", "lecture", "lesson", "tutorial", "homework", "exam", "quiz", "assignment", "课程", "教程", "课堂", "作业", "考试", "题目", "学习", "网课"], urlKeywords: ["course", "learn", "lecture", "lesson", "homework"], weightedKeywords: { course: 25, lecture: 20, lesson: 20, 课程: 25, 学习: 20, 作业: 20, 考试: 20 }, minScore: 40 },
  { id: "thesis", name: "毕业论文", color: "red", domains: ["docs.google.com", "office.com", "overleaf.com", "cnki.net"], domainSuffixes: [], titleKeywords: ["毕业论文", "开题报告", "中期报告", "答辩", "论文格式", "致谢", "摘要", "参考文献", "thesis", "dissertation", "defense", "proposal", "毕设", "毕业设计"], urlKeywords: ["thesis", "dissertation", "defense", "proposal"], weightedKeywords: { 毕业论文: 40, 毕业设计: 35, 毕设: 35, 答辩: 30, 开题报告: 30, 中期报告: 30, 参考文献: 25, thesis: 30, defense: 25 }, minScore: 35 },
  { id: "work", name: "工作办公", color: "grey", domains: ["notion.so", "feishu.cn", "larksuite.com", "yuque.com", "office.com", "docs.google.com", "sheets.google.com", "slides.google.com", "trello.com", "asana.com", "linear.app", "jira.com"], domainSuffixes: [], titleKeywords: ["document", "spreadsheet", "presentation", "meeting", "project", "task", "roadmap", "plan", "文档", "表格", "幻灯片", "会议", "项目", "任务", "计划", "看板", "协作"], urlKeywords: ["doc", "sheet", "slide", "task", "project", "board"], weightedKeywords: { meeting: 20, project: 20, task: 18, 文档: 20, 会议: 20, 项目: 20, 任务: 18 }, minScore: 40 },
  { id: "mail", name: "邮件通讯", color: "blue", domains: ["mail.google.com", "gmail.com", "outlook.live.com", "outlook.office.com", "mail.qq.com", "163.com"], domainSuffixes: [], titleKeywords: ["mail", "inbox", "email", "outlook", "gmail", "unread", "邮件", "收件箱", "发件箱"], urlKeywords: ["mail", "inbox"], weightedKeywords: { mail: 25, email: 25, inbox: 20, 邮件: 25, 收件箱: 20 }, minScore: 35 },
  { id: "cloud-files", name: "云盘文档", color: "cyan", domains: ["drive.google.com", "dropbox.com", "onedrive.live.com", "icloud.com", "pan.baidu.com", "aliyundrive.com"], domainSuffixes: [], titleKeywords: ["drive", "cloud", "file", "folder", "share", "download", "upload", "云盘", "网盘", "文件", "文件夹", "分享", "下载", "上传"], urlKeywords: ["drive", "file", "folder", "share", "download"], weightedKeywords: { drive: 20, file: 15, folder: 15, 云盘: 25, 网盘: 25, 文件: 15 }, minScore: 40 },
  { id: "social", name: "社交社区", color: "pink", domains: ["x.com", "twitter.com", "reddit.com", "zhihu.com", "douban.com", "weibo.com", "tieba.baidu.com", "discord.com"], domainSuffixes: [], titleKeywords: ["reddit", "twitter", "x", "zhihu", "douban", "weibo", "post", "comment", "community", "知乎", "豆瓣", "微博", "贴吧", "社区", "评论", "帖子"], urlKeywords: ["post", "status", "comment", "topic"], weightedKeywords: { reddit: 25, zhihu: 25, 知乎: 25, 微博: 25, 社区: 18, 评论: 15 }, minScore: 40 },
  { id: "news", name: "新闻资讯", color: "orange", domains: ["news.google.com", "bbc.com", "cnn.com", "nytimes.com", "theguardian.com", "reuters.com", "apnews.com", "36kr.com", "huxiu.com", "ifeng.com", "qq.com", "sina.com.cn"], domainSuffixes: [], titleKeywords: ["news", "breaking", "report", "article", "latest", "新闻", "资讯", "报道", "快讯", "热点", "最新"], urlKeywords: ["news", "article", "report"], weightedKeywords: { news: 25, breaking: 20, article: 15, 新闻: 25, 资讯: 20, 报道: 18 }, minScore: 40 },
  { id: "video", name: "视频娱乐", color: "red", domains: ["youtube.com", "bilibili.com", "netflix.com", "twitch.tv", "iqiyi.com", "youku.com", "v.qq.com"], domainSuffixes: [], titleKeywords: ["video", "watch", "youtube", "bilibili", "anime", "movie", "episode", "live", "视频", "播放", "电影", "动漫", "番剧", "直播"], urlKeywords: ["watch", "video", "live", "episode"], weightedKeywords: { video: 20, watch: 15, youtube: 25, bilibili: 25, 视频: 25, 电影: 20, 动漫: 20, 直播: 20 }, minScore: 40 },
  { id: "music", name: "音乐音频", color: "purple", domains: ["music.apple.com", "open.spotify.com", "spotify.com", "soundcloud.com", "music.youtube.com", "music.163.com", "y.qq.com"], domainSuffixes: [], titleKeywords: ["music", "song", "album", "playlist", "podcast", "音乐", "歌曲", "专辑", "歌单", "播客"], urlKeywords: ["music", "playlist", "album", "track", "podcast"], weightedKeywords: { music: 25, song: 20, album: 20, playlist: 20, 音乐: 25, 歌曲: 20, 歌单: 20 }, minScore: 35 },
  { id: "shopping", name: "购物消费", color: "yellow", domains: ["amazon.com", "taobao.com", "tmall.com", "jd.com", "ebay.com", "aliexpress.com", "pinduoduo.com", "smzdm.com"], domainSuffixes: [], titleKeywords: ["buy", "price", "cart", "order", "product", "review", "discount", "coupon", "购买", "价格", "购物车", "订单", "商品", "优惠", "折扣", "评价"], urlKeywords: ["product", "item", "cart", "order", "buy"], weightedKeywords: { buy: 20, price: 20, cart: 25, order: 20, product: 15, 购买: 20, 价格: 20, 订单: 20, 购物车: 25 }, minScore: 35 },
  { id: "finance", name: "金融支付", color: "green", domains: ["paypal.com", "alipay.com", "wise.com", "coinbase.com", "binance.com"], domainSuffixes: ["bank"], titleKeywords: ["bank", "payment", "invoice", "bill", "wallet", "finance", "stock", "crypto", "支付", "银行", "账单", "发票", "钱包", "股票", "基金", "加密货币"], urlKeywords: ["payment", "invoice", "wallet", "bill", "trade"], weightedKeywords: { payment: 25, bank: 25, invoice: 20, wallet: 20, 支付: 25, 银行: 25, 账单: 20, 发票: 20 }, minScore: 40 },
  { id: "travel", name: "旅行出行", color: "orange", domains: ["booking.com", "airbnb.com", "trip.com", "ctrip.com", "maps.google.com", "flights.google.com", "uber.com"], domainSuffixes: [], titleKeywords: ["hotel", "flight", "train", "map", "route", "booking", "travel", "酒店", "机票", "火车", "地图", "路线", "旅行", "出行", "预订"], urlKeywords: ["hotel", "flight", "travel", "booking", "map", "route"], weightedKeywords: { hotel: 25, flight: 25, travel: 20, map: 15, 酒店: 25, 机票: 25, 旅行: 20, 地图: 15 }, minScore: 35 },
  { id: "life", name: "生活服务", color: "green", domains: ["meituan.com", "ele.me", "dianping.com", "yelp.com"], domainSuffixes: [], titleKeywords: ["restaurant", "food", "delivery", "weather", "map", "service", "外卖", "餐厅", "美食", "天气", "服务", "本地"], urlKeywords: ["restaurant", "food", "delivery", "weather"], weightedKeywords: { food: 20, delivery: 20, weather: 20, 外卖: 25, 餐厅: 20, 天气: 20 }, minScore: 40 },
  { id: "design", name: "设计素材", color: "pink", domains: ["figma.com", "canva.com", "dribbble.com", "behance.net", "iconfont.cn", "flaticon.com", "unsplash.com"], domainSuffixes: [], titleKeywords: ["design", "figma", "icon", "template", "color", "font", "ui", "ux", "mockup", "设计", "图标", "模板", "配色", "字体", "界面", "素材"], urlKeywords: ["design", "icon", "template", "font", "color"], weightedKeywords: { figma: 30, design: 20, icon: 20, template: 18, 设计: 25, 图标: 20, 模板: 18 }, minScore: 35 },
  { id: "images", name: "图片资源", color: "cyan", domains: ["unsplash.com", "pexels.com", "pixabay.com", "pinterest.com", "images.google.com"], domainSuffixes: [], titleKeywords: ["image", "photo", "picture", "wallpaper", "png", "svg", "图片", "照片", "壁纸", "素材", "背景图"], urlKeywords: ["image", "photo", "picture", "wallpaper"], weightedKeywords: { image: 20, photo: 20, picture: 20, wallpaper: 20, 图片: 25, 照片: 20, 壁纸: 20 }, minScore: 35 },
  { id: "games", name: "游戏娱乐", color: "purple", domains: ["steampowered.com", "store.steampowered.com", "epicgames.com", "ign.com", "gamespot.com"], domainSuffixes: [], titleKeywords: ["game", "steam", "epic games", "gameplay", "游戏", "电玩", "攻略", "评分"], urlKeywords: ["game", "store", "app"], weightedKeywords: { game: 25, steam: 25, 游戏: 25, 攻略: 20 }, minScore: 35 }
];
